### ISSUE TITLE
Default image style missing?

### ISSUE THREAD

**Issue by jgottwig** [UMD-Digital/umd_terp#3]
The theme looks good. I've installed this (master branch) on 8.8.5 and am starting to explore it now.

I did get the following error after creating a Terp Homepage document:

Error: Call to a member function buildUrl() on null in umd_terp_preprocess_page() (line 42 of /apps/git/drupal-hosts/demo/web/themes/contrib/umd_terp/inc/preprocess.inc) 

Which looks to be because I don't have an "optimized" image style.

$variables['hero_image'] = ImageStyle::load('optimized')->buildUrl($hero_uri);

Is there a particular image optimizer module you're using that generates this style? I can create something myself but want to make sure it matches with what the theme expects.

**Comment by drogers98** [comment]
Jeremy, we use https://www.drupal.org/project/imageapi_optimize in the starter theme, that's what we would recommend. Then just create image style "optimized", set it to use whatever optimization library you wish, and should be set.

Since we are on a bit of a holding pattern with UMD DIT as far as how we are packaging the theme/module/etc into more of an install profile or similar, we haven't fully tested 0 config installs, just FYI, there may be other similar small issues that arise.

**Comment by jgottwig** [comment]
Ok, thanks so much.

It's good to hear an install profile is in the works even if it's on hold. I was considering building one myself for the libraries using the terp_* stuff as a foundation, but maybe I'll wait until yours moves forward.
